/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  auth: {
    ForgotPassword: () => import('#modules/auth/controllers/forgot_password_controller'),
    Login: () => import('#modules/auth/controllers/login_controller'),
    Logout: () => import('#modules/auth/controllers/logout_controller'),
    Register: () => import('#modules/auth/controllers/register_controller'),
    ResetPassword: () => import('#modules/auth/controllers/reset_password_controller'),
  },
  core: {
    Home: () => import('#modules/core/controllers/home_controller'),
    ShowMedia: () => import('#modules/core/controllers/show_media_controller'),
  },
  wishlists: {
    categories: {
      CreateWishlistCategories: () => import('#modules/wishlists/controllers/categories/create_wishlist_categories_controller'),
      EditWishlistCategories: () => import('#modules/wishlists/controllers/categories/edit_wishlist_categories_controller'),
      RemoveWishlistCategories: () => import('#modules/wishlists/controllers/categories/remove_wishlist_categories_controller'),
    },
    gifts: {
      BookGifts: () => import('#modules/wishlists/controllers/gifts/book_gifts_controller'),
      CreateGifts: () => import('#modules/wishlists/controllers/gifts/create_gifts_controller'),
      EditGifts: () => import('#modules/wishlists/controllers/gifts/edit_gifts_controller'),
      RemoveGifts: () => import('#modules/wishlists/controllers/gifts/remove_gifts_controller'),
    },
    wishlists: {
      CreateWishlists: () => import('#modules/wishlists/controllers/wishlists/create_wishlists_controller'),
      EditWishlists: () => import('#modules/wishlists/controllers/wishlists/edit_wishlists_controller'),
      ShowWishlists: () => import('#modules/wishlists/controllers/wishlists/show_wishlists_controller'),
    },
  },
}
