/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

import type { InferSharedProps, InferFlashData } from '@adonisjs/inertia/types'
/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'

import type InertiaMiddleware from '#middleware/inertia_middleware'
import type AuthUserTransformer from '#modules/auth/transformers/user_transformer'
import type AuthUserListTransformer from '#modules/auth/transformers/user_list_transformer'
import type WishlistsWishlistTransformer from '#modules/wishlists/transformers/wishlist_transformer'
import type WishlistsWishlistGiftTransformer from '#modules/wishlists/transformers/wishlist_gift_transformer'
import type WishlistsWishlistThemeTransformer from '#modules/wishlists/transformers/wishlist_theme_transformer'
import type WishlistsWishlistCategoryTransformer from '#modules/wishlists/transformers/wishlist_category_transformer'

export namespace Data {
  export namespace Auth {
    export type UserList = InferData<AuthUserListTransformer>
    export namespace UserList {
      export type Variants = InferVariants<AuthUserListTransformer>
    }
    export type User = InferData<AuthUserTransformer>
    export namespace User {
      export type Variants = InferVariants<AuthUserTransformer>
    }
  }
  export namespace Wishlists {
    export type WishlistCategory = InferData<WishlistsWishlistCategoryTransformer>
    export namespace WishlistCategory {
      export type Variants = InferVariants<WishlistsWishlistCategoryTransformer>
    }
    export type WishlistGift = InferData<WishlistsWishlistGiftTransformer>
    export namespace WishlistGift {
      export type Variants = InferVariants<WishlistsWishlistGiftTransformer>
    }
    export type WishlistTheme = InferData<WishlistsWishlistThemeTransformer>
    export namespace WishlistTheme {
      export type Variants = InferVariants<WishlistsWishlistThemeTransformer>
    }
    export type Wishlist = InferData<WishlistsWishlistTransformer>
    export namespace Wishlist {
      export type Variants = InferVariants<WishlistsWishlistTransformer>
    }
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
  export type FlashMessages = InferFlashData<InertiaMiddleware>
}
